---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-pord
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:isaacnikon/k8s-deployments.git
    targetRevision: HEAD
    path: environments/pord/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true